version: '3.8'

services:
  jdbc-connector:
    image: libelulasoft/ibm-informix-db-connector
    network_mode: host
    ports:
      - "5690:5690"
    environment:
      - "SPRING_DEVTOOLS_RESTART_ENABLED=true"
      - "SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=5s"
      - "SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s"
      - "SPRING_DATASOURCE_URL=jdbc:informix-sqli://172.18.42.11:1525/asisken:INFORMIXSERVER=dev_asisken"
      - "SPRING_DATASOURCE_USERNAME=macsys"
      - "SPRING_DATASOURCE_PASSWORD=macsys"
      - "SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.informix.jdbc.IfxDriver"
      - "SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10"
      - "SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=2"
      - "SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000"
      - "SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=600000"
      - "SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1800000"
      - "SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD=60000"
      - "SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT=5000"
      - "SPRING_DATASOURCE_HIKARI_CONNECTION_TEST_QUERY=SELECT * FROM am_comunica"
  fastapi-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1